#!/usr/bin/env python3
# Pull the field-math functions VERBATIM out of the shipped headers into a single .inc that
# the host equivalence harness compiles. Extracting (rather than re-typing) is the point:
# the harness must exercise the code that actually builds, so a transcription slip cannot
# make a broken port look correct.
#
#   python3 tests/extract_field.py            # writes tests/field_extract.inc
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..'))

# (output file, source file, [function names]) -- order matters, definitions precede uses.
# Split across two .inc files so the include-check can pull in the RCKangaroo dependencies
# and then compile the REAL field_split.cuh, rather than a copy of its contents.
SOURCES = [
    ('field_extract_rck.inc', os.path.join(ROOT, 'third_party', 'RCKangaroo', 'RCGpuUtils.h'), [
        'add_320_to_256',
        'mul_256_by_P0inv',
        'mul_256_by_64',
        'MulModP',
        'add_320_to_256s',
        'SqrModP',
    ]),
    ('field_extract_split.inc', os.path.join(ROOT, 'field_split.cuh'), [
        'mul512_split',
        'sqr512_split',
        'MulModP_split',
        'SqrModP_split',
    ]),
]


def extract(src_text, name):
    """Grab `__device__ ... name(...) { ... }` up to the closing brace in column 0."""
    pat = re.compile(
        r'^__device__[^\n]*\b' + re.escape(name) + r'\s*\([^\n]*$', re.M)
    m = pat.search(src_text)
    if not m:
        sys.exit('extract: %s not found' % name)
    start = m.start()
    end = src_text.find('\n}\n', start)
    if end < 0:
        sys.exit('extract: %s has no column-0 closing brace' % name)
    return src_text[start:end + 3]


def main():
    for dstname, path, names in SOURCES:
        text = open(path).read().replace('\r\n', '\n')
        rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
        out = [
            '// AUTO-GENERATED by tests/extract_field.py -- do not edit.',
            '// Verbatim function bodies lifted from %s.' % rel,
            '',
        ]
        for n in names:
            body = extract(text, n)
            # The split cores are emitted against the short macro spellings, which
            # field_split.cuh aliases onto the _32 macros. The harness defines the _32
            # names, so apply the same aliasing here.
            body = re.sub(r'\bmad_lo_cc\(', 'mad_lo_cc_32(', body)
            body = re.sub(r'\bmadc_hi_cc\(', 'madc_hi_cc_32(', body)
            body = re.sub(r'\bmadc_lo_cc\(', 'madc_lo_cc_32(', body)
            out.append(body)
            out.append('')

        with open(os.path.join(HERE, dstname), 'w', newline='\n') as f:
            f.write('\n'.join(out))
        print('%s: %d functions extracted' % (dstname, len(names)))


if __name__ == '__main__':
    main()
