#!/usr/bin/env python3
# Lift mul_256_by_P0inv verbatim out of RCGpuUtils.h for the host test. The rest of that header
# can't be host-included (its PTX macros are inline asm); field_split.cuh is included directly.
#   python3 tests/extract_field.py   ->  tests/field_extract_rck.inc
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'third_party', 'RCKangaroo', 'RCGpuUtils.h')
NAME = 'mul_256_by_P0inv'

text = open(SRC).read().replace('\r\n', '\n')
m = re.search(r'^__device__[^\n]*\b' + NAME + r'\s*\([^\n]*$', text, re.M)
if not m:
    sys.exit('extract: %s not found' % NAME)
end = text.find('\n}\n', m.start())
if end < 0:
    sys.exit('extract: %s has no column-0 closing brace' % NAME)

with open(os.path.join(HERE, 'field_extract_rck.inc'), 'w', newline='\n') as f:
    f.write('// AUTO-GENERATED by tests/extract_field.py -- do not edit.\n\n')
    f.write(text[m.start():end + 3])
print('field_extract_rck.inc: %s extracted' % NAME)
